### ISSUE TITLE
"Forgot Password" Button is non functioning 

### ISSUE THREAD

**Issue by thesoundbyle** [DDMAL/mei-mapping-tool#234] opened 2021-05-28 19:32 UTC
![Screenshot_2](https://user-images.githubusercontent.com/62864127/120033657-dc487580-bfc9-11eb-9c40-f05b027a4ba1.jpg)

**Comment by timothydereuse** [comment] 2023-04-28 20:30
Duplicate of https://github.com/DDMAL/mei-mapping-tool/issues/239.

**Closed as completed by timothydereuse** 2023-04-28 20:30 UTC
